# Generated by Django 4.1.4 on 2022-12-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun_uz_t', models.CharField(max_length=200)),
                ('kun_uz_img', models.URLField(blank=True, null=True)),
                ('kun_uz_l', models.TextField()),
                ('uzre_t', models.CharField(max_length=200)),
                ('uzre_img', models.URLField(blank=True, null=True)),
                ('uzre_l', models.TextField()),
                ('bbc_t', models.CharField(max_length=200)),
                ('bbc_img', models.URLField(blank=True, null=True)),
                ('bbc_l', models.TextField()),
                ('gaz_t', models.CharField(max_length=200)),
                ('gaz_img', models.URLField(blank=True, null=True)),
                ('gaz_l', models.TextField()),
                ('daily_t', models.CharField(max_length=200)),
                ('daily_img', models.URLField(blank=True, null=True)),
                ('daily_l', models.TextField()),
                ('qal_t', models.CharField(max_length=200)),
                ('qal_img', models.URLField(blank=True, null=True)),
                ('qal_l', models.TextField()),
                ('dar_t', models.CharField(max_length=200)),
                ('dar_img', models.URLField(blank=True, null=True)),
                ('dar_l', models.TextField()),
                ('aniq_t', models.CharField(max_length=200)),
                ('aniq_img', models.URLField(blank=True, null=True)),
                ('aniq_l', models.TextField()),
                ('side_t', models.CharField(max_length=200)),
                ('side_img', models.URLField(blank=True, null=True)),
                ('side_l', models.TextField()),
                ('sport_t', models.CharField(max_length=200)),
                ('sport_img', models.URLField(blank=True, null=True)),
                ('sport_l', models.TextField()),
                ('uz24_t', models.CharField(max_length=200)),
                ('uz24_img', models.URLField(blank=True, null=True)),
                ('uz24_l', models.TextField()),
                ('nuz_t', models.CharField(max_length=200)),
                ('nuz_img', models.URLField(blank=True, null=True)),
                ('nuz_l', models.TextField()),
                ('kr_t', models.CharField(max_length=200)),
                ('kr_img', models.URLField(blank=True, null=True)),
                ('kr_l', models.TextField()),
                ('sputnik_t', models.CharField(max_length=200)),
                ('sputnik_img', models.URLField(blank=True, null=True)),
                ('sputnik_l', models.TextField()),
                ('samnews_t', models.CharField(max_length=200)),
                ('samnews_img', models.URLField(blank=True, null=True)),
                ('samnews_l', models.TextField()),
                ('uza_t', models.CharField(max_length=200)),
                ('uza_img', models.URLField(blank=True, null=True)),
                ('uza_l', models.TextField()),
                ('zamin_t', models.CharField(max_length=200)),
                ('zamin_img', models.URLField(blank=True, null=True)),
                ('zamin_l', models.TextField()),
                ('matbuot_t', models.CharField(max_length=200)),
                ('matbuot_img', models.URLField(blank=True, null=True)),
                ('matbuot_l', models.TextField()),
                ('bugun_t', models.CharField(max_length=200)),
                ('bugun_img', models.URLField(blank=True, null=True)),
                ('bugun_l', models.TextField()),
                ('antimon_t', models.CharField(max_length=200)),
                ('antimon_img', models.URLField(blank=True, null=True)),
                ('antimon_l', models.TextField()),
            ],
        ),
    ]
