# Generated by Django 4.1.4 on 2022-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dar_t', models.CharField(max_length=200)),
                ('dar_img', models.URLField(blank=True, null=True)),
                ('dar_l', models.TextField()),
                ('uzre_t', models.CharField(max_length=200)),
                ('uzre_img', models.URLField(blank=True, null=True)),
                ('uzre_l', models.TextField()),
                ('bbc_t', models.CharField(max_length=200)),
                ('bbc_img', models.URLField(blank=True, null=True)),
                ('bbc_l', models.TextField()),
                ('gaz_t', models.CharField(max_length=200)),
                ('gaz_img', models.URLField(blank=True, null=True)),
                ('gaz_l', models.TextField()),
                ('daily_t', models.CharField(max_length=200)),
                ('daily_img', models.URLField(blank=True, null=True)),
                ('daily_l', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='dar_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dar_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='dar_t',
        ),
    ]
