# Generated by Django 4.1.4 on 2022-12-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sport_remove_news_dar_img_remove_news_dar_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='uzre_img',
            new_name='side_img',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='uzre_l',
            new_name='side_l',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='uzre_t',
            new_name='side_t',
        ),
        migrations.RemoveField(
            model_name='news',
            name='side_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='side_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='side_t',
        ),
    ]
