# Generated by Django 4.1.4 on 2022-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_sport_img_remove_news_sport_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniq_t', models.CharField(max_length=200)),
                ('aniq_img', models.URLField(blank=True, null=True)),
                ('aniq_l', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='aniq_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='aniq_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='aniq_t',
        ),
    ]
