# Generated by Django 4.1.4 on 2022-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_politics_remove_news_aniq_img_remove_news_aniq_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='antimon_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='antimon_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='antimon_t',
        ),
        migrations.AddField(
            model_name='politics',
            name='antimon_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='antimon_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='antimon_t',
            field=models.CharField(default='q', max_length=200),
            preserve_default=False,
        ),
    ]
