# Generated by Django 4.1.4 on 2022-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_antimon_img_remove_news_antimon_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='uz24_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='uz24_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='uz24_t',
        ),
        migrations.AddField(
            model_name='politics',
            name='uz24_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='uz24_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='uz24_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
