# Generated by Django 4.1.4 on 2022-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_uz24_img_remove_news_uz24_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='nuz_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='nuz_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='nuz_t',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='gaz_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='gaz_l',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='gaz_t',
        ),
        migrations.AddField(
            model_name='sport',
            name='nuz_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='nuz_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='nuz_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
