# Generated by Django 4.1.4 on 2022-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_nuz_img_remove_news_nuz_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bbc_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bbc_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bbc_t',
        ),
        migrations.AddField(
            model_name='politics',
            name='bbc_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='bbc_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='bbc_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
