# Generated by Django 4.1.4 on 2022-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_news_bbc_img_remove_news_bbc_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='kr_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='kr_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='kr_t',
        ),
        migrations.AddField(
            model_name='politics',
            name='pr_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='pr_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='pr_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
