# Generated by Django 4.1.4 on 2022-12-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_kr_img_remove_news_kr_l_remove_news_kr_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sputnik_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sputnik_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sputnik_t',
        ),
        migrations.AddField(
            model_name='sport',
            name='sputnik_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='sputnik_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='sputnik_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
