# Generated by Django 4.1.4 on 2022-12-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_news_sputnik_img_remove_news_sputnik_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samnews_t', models.CharField(max_length=200)),
                ('samnews_img', models.URLField(blank=True, null=True)),
                ('samnews_l', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='samnews_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='samnews_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='samnews_t',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='daily_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='daily_l',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='daily_t',
        ),
    ]
