# Generated by Django 4.1.4 on 2022-12-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_economy_remove_news_samnews_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='zamin_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='zamin_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='zamin_t',
        ),
        migrations.AddField(
            model_name='economy',
            name='zamin_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economy',
            name='zamin_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='economy',
            name='zamin_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
