# Generated by Django 4.1.4 on 2022-12-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_news_zamin_img_remove_news_zamin_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bugun_img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bugun_l',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bugun_t',
        ),
        migrations.AddField(
            model_name='economy',
            name='bugun_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economy',
            name='bugun_l',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='economy',
            name='bugun_t',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
    ]
