# Generated by Django 4.1.4 on 2022-12-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_news_bugun_img_remove_news_bugun_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='uza_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economy',
            name='uza_l',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='economy',
            name='uza_t',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
