# Generated by Django 4.1.5 on 2023-01-07 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_post_body_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='dar_l',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='dar_img',
            new_name='body_image',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='nuz_img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='dar_t',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='nuz_l',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='nuz_t',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='side_img1',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='side_l1',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='side_t1',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_l',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_t',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sputnik_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sputnik_l',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sputnik_t',
        ),
        migrations.AddField(
            model_name='sport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
