# Generated by Django 4.1.5 on 2023-01-08 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_rename_dar_l_sport_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Economy',
        ),
        migrations.RenameField(
            model_name='politics',
            old_name='aniq_l',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='politics',
            old_name='aniq_img',
            new_name='body_image',
        ),
        migrations.RenameField(
            model_name='politics',
            old_name='antimon_img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='aniq_t',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='antimon_l',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='antimon_t',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='bbc_img',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='bbc_l',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='bbc_t',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='pr_img',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='pr_l',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='pr_t',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='uz24_img',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='uz24_l',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='uz24_t',
        ),
        migrations.AddField(
            model_name='politics',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politics',
            name='title',
            field=models.CharField(default=6.178942165101334e-05, max_length=255),
            preserve_default=False,
        ),
    ]
